import type { NavMenu, NavMenuItems } from '~/types/nav'

export const navMenu: NavMenu[] = [
  {
    heading: 'General',
    headingKey: 'nav.general',
    items: [
      {
        title: 'Dashboard',
        titleKey: 'nav.dashboard',
        icon: 'i-lucide-layout-dashboard',
        link: '/',
      },
      {
        title: 'Email',
        titleKey: 'nav.email',
        icon: 'i-lucide-mail',
        link: '/email',
      },
      {
        title: 'Tasks',
        titleKey: 'nav.tasks',
        icon: 'i-lucide-calendar-check-2',
        link: '/tasks',
      },
    ],
  },
  {
    heading: 'Apps',
    headingKey: 'nav.apps',
    items: [
      {
        title: 'Kanban Board',
        titleKey: 'nav.kanbanBoard',
        icon: 'i-lucide-kanban',
        link: '/kanban',
        new: true,
      },
      {
        title: 'Gantt Chart',
        titleKey: 'nav.ganttChart',
        icon: 'i-lucide-gantt-chart',
        link: '/gantt',
        new: true,
      },
    ],
  },
  {
    heading: 'CRM',
    headingKey: 'nav.crm',
    items: [
      {
        title: 'Contacts',
        titleKey: 'nav.contacts',
        icon: 'i-lucide-contact',
        link: '/crm/contacts',
      },
      {
        title: 'Leads',
        titleKey: 'nav.leads',
        icon: 'i-lucide-magnet',
        link: '/crm/leads',
      },
      {
        title: 'Deals Pipeline',
        titleKey: 'nav.dealsPipeline',
        icon: 'i-lucide-handshake',
        link: '/crm/deals',
        new: true,
      },
      {
        title: 'Companies',
        titleKey: 'nav.companies',
        icon: 'i-lucide-building-2',
        link: '/crm/companies',
      },
      {
        title: 'Activities',
        titleKey: 'nav.activities',
        icon: 'i-lucide-activity',
        link: '/crm/activities',
      },
    ],
  },
  {
    heading: 'Sales & Commerce',
    headingKey: 'nav.salesCommerce',
    items: [
      {
        title: 'Quotes',
        titleKey: 'nav.quotes',
        icon: 'i-lucide-file-text',
        link: '/sales/quotes',
      },
      {
        title: 'Invoices',
        titleKey: 'nav.invoices',
        icon: 'i-lucide-receipt',
        link: '/sales/invoices',
      },
      {
        title: 'Orders',
        titleKey: 'nav.orders',
        icon: 'i-lucide-shopping-cart',
        link: '/sales/orders',
      },
      {
        title: 'Products',
        titleKey: 'nav.products',
        icon: 'i-lucide-package',
        link: '/sales/products',
      },
      {
        title: 'Customers',
        titleKey: 'nav.customers',
        icon: 'i-lucide-users',
        link: '/sales/customers',
      },
    ],
  },
  {
    heading: 'Inventory & Warehouse',
    headingKey: 'nav.inventoryWarehouse',
    items: [
      {
        title: 'Stock Overview',
        titleKey: 'nav.stockOverview',
        icon: 'i-lucide-warehouse',
        link: '/inventory/stock',
      },
      {
        title: 'Transfers',
        titleKey: 'nav.transfers',
        icon: 'i-lucide-arrow-left-right',
        link: '/inventory/transfers',
      },
      {
        title: 'Purchase Orders',
        titleKey: 'nav.purchaseOrders',
        icon: 'i-lucide-clipboard-list',
        link: '/inventory/purchase-orders',
      },
      {
        title: 'Vendors',
        titleKey: 'nav.vendors',
        icon: 'i-lucide-truck',
        link: '/inventory/vendors',
      },
    ],
  },
  {
    heading: 'HR & Workforce',
    headingKey: 'nav.hrWorkforce',
    items: [
      {
        title: 'Employees',
        titleKey: 'nav.employees',
        icon: 'i-lucide-user-round-check',
        link: '/hr/employees',
      },
      {
        title: 'Attendance',
        titleKey: 'nav.attendance',
        icon: 'i-lucide-clock',
        link: '/hr/attendance',
      },
      {
        title: 'Payroll',
        titleKey: 'nav.payroll',
        icon: 'i-lucide-banknote',
        link: '/hr/payroll',
      },
      {
        title: 'Recruitment',
        titleKey: 'nav.recruitment',
        icon: 'i-lucide-briefcase',
        link: '/hr/recruitment',
      },
      {
        title: 'Leave Mgmt',
        titleKey: 'nav.leaveMgmt',
        icon: 'i-lucide-calendar-off',
        link: '/hr/leaves',
      },
    ],
  },
  {
    heading: 'Finance & Accounting',
    headingKey: 'nav.financeAccounting',
    items: [
      {
        title: 'Accounts',
        titleKey: 'nav.accounts',
        icon: 'i-lucide-wallet',
        link: '/finance/accounts',
      },
      {
        title: 'Transactions',
        titleKey: 'nav.transactions',
        icon: 'i-lucide-arrow-right-left',
        link: '/finance/transactions',
      },
      {
        title: 'Expenses',
        titleKey: 'nav.expenses',
        icon: 'i-lucide-credit-card',
        link: '/finance/expenses',
      },
      {
        title: 'Tax Management',
        titleKey: 'nav.taxManagement',
        icon: 'i-lucide-percent',
        link: '/finance/taxes',
      },
      {
        title: 'Balance Sheet',
        titleKey: 'nav.balanceSheet',
        icon: 'i-lucide-landmark',
        link: '/finance/balance-sheet',
        new: true,
      },
      {
        title: 'Income Statement',
        titleKey: 'nav.incomeStatement',
        icon: 'i-lucide-receipt',
        link: '/finance/income-statement',
        new: true,
      },
      {
        title: 'Financial Ratios',
        titleKey: 'nav.financialRatios',
        icon: 'i-lucide-chart-no-axes-combined',
        link: '/finance/ratios',
        new: true,
      },
      {
        title: 'Business Health',
        titleKey: 'nav.businessHealth',
        icon: 'i-lucide-heart-pulse',
        link: '/finance/business-health',
        new: true,
      },
    ],
  },
  {
    heading: 'Project Management',
    headingKey: 'nav.projectManagement',
    items: [
      {
        title: 'Projects',
        titleKey: 'nav.projects',
        icon: 'i-lucide-folder-kanban',
        link: '/projects/list',
      },
      {
        title: 'Timesheets',
        titleKey: 'nav.timesheets',
        icon: 'i-lucide-timer',
        link: '/projects/timesheets',
      },
      {
        title: 'Milestones',
        titleKey: 'nav.milestones',
        icon: 'i-lucide-flag',
        link: '/projects/milestones',
      },
    ],
  },
  {
    heading: 'Support',
    headingKey: 'nav.support',
    items: [
      {
        title: 'Tickets',
        titleKey: 'nav.tickets',
        icon: 'i-lucide-ticket',
        link: '/support/tickets',
      },
      {
        title: 'Knowledge Base',
        titleKey: 'nav.knowledgeBase',
        icon: 'i-lucide-book-open',
        link: '/support/knowledge-base',
      },
      {
        title: 'Live Chat',
        titleKey: 'nav.liveChat',
        icon: 'i-lucide-message-circle',
        link: '/support/chat',
        new: true,
      },
    ],
  },
  {
    heading: 'Marketing',
    headingKey: 'nav.marketing',
    items: [
      {
        title: 'Campaigns',
        titleKey: 'nav.campaigns',
        icon: 'i-lucide-megaphone',
        link: '/marketing/campaigns',
      },
      {
        title: 'Email Blasts',
        titleKey: 'nav.emailBlasts',
        icon: 'i-lucide-mails',
        link: '/marketing/email-blasts',
      },
      {
        title: 'Analytics',
        titleKey: 'nav.analytics',
        icon: 'i-lucide-bar-chart-3',
        link: '/marketing/analytics',
      },
    ],
  },
  {
    heading: 'Reports',
    headingKey: 'nav.reports',
    items: [
      {
        title: 'Sales Reports',
        titleKey: 'nav.salesReports',
        icon: 'i-lucide-trending-up',
        link: '/reports/sales',
      },
      {
        title: 'Financial Reports',
        titleKey: 'nav.financialReports',
        icon: 'i-lucide-pie-chart',
        link: '/reports/financial',
      },
      {
        title: 'HR Reports',
        titleKey: 'nav.hrReports',
        icon: 'i-lucide-file-bar-chart',
        link: '/reports/hr',
      },
    ],
  },
  {
    heading: 'Pages',
    headingKey: 'nav.pages',
    items: [
      {
        title: 'Authentication',
        titleKey: 'nav.authentication',
        icon: 'i-lucide-lock-keyhole-open',
        children: [
          { title: 'Login', titleKey: 'nav.login', icon: 'i-lucide-circle', link: '/login' },
          { title: 'Login Basic', titleKey: 'nav.loginBasic', icon: 'i-lucide-circle', link: '/login-basic' },
          { title: 'Register', titleKey: 'nav.register', icon: 'i-lucide-circle', link: '/register' },
          { title: 'Forgot Password', titleKey: 'nav.forgotPassword', icon: 'i-lucide-circle', link: '/forgot-password' },
          { title: 'OTP', titleKey: 'nav.otp', icon: 'i-lucide-circle', link: '/otp' },
          { title: 'OTP 1', icon: 'i-lucide-circle', link: '/otp-1' },
          { title: 'OTP 2', icon: 'i-lucide-circle', link: '/otp-2' },
        ],
      },
      {
        title: 'Errors',
        titleKey: 'nav.errors',
        icon: 'i-lucide-triangle-alert',
        children: [
          { title: '401 - Unauthorized', icon: 'i-lucide-circle', link: '/401' },
          { title: '403 - Forbidden', icon: 'i-lucide-circle', link: '/403' },
          { title: '404 - Not Found', icon: 'i-lucide-circle', link: '/404' },
          { title: '500 - Internal Server Error', icon: 'i-lucide-circle', link: '/500' },
          { title: '503 - Service Unavailable', icon: 'i-lucide-circle', link: '/503' },
        ],
      },
      {
        title: 'Settings',
        titleKey: 'nav.settings',
        icon: 'i-lucide-settings',
        new: true,
        children: [
          { title: 'Profile', titleKey: 'nav.profile', icon: 'i-lucide-circle', link: '/settings/profile' },
          { title: 'Account', titleKey: 'nav.account', icon: 'i-lucide-circle', link: '/settings/account' },
          { title: 'Appearance', titleKey: 'nav.appearance', icon: 'i-lucide-circle', link: '/settings/appearance' },
          { title: 'Notifications', titleKey: 'nav.notifications', icon: 'i-lucide-circle', link: '/settings/notifications' },
          { title: 'Display', titleKey: 'nav.display', icon: 'i-lucide-circle', link: '/settings/display' },
        ],
      },
    ],
  },
  {
    heading: 'Components',
    headingKey: 'nav.components',
    items: [
      {
        title: 'Components',
        titleKey: 'nav.components',
        icon: 'i-lucide-component',
        children: [
          { title: 'Accordion', icon: 'i-lucide-circle', link: '/components/accordion' },
          { title: 'Alert', icon: 'i-lucide-circle', link: '/components/alert' },
          { title: 'Alert Dialog', icon: 'i-lucide-circle', link: '/components/alert-dialog' },
          { title: 'Aspect Ratio', icon: 'i-lucide-circle', link: '/components/aspect-ratio' },
          { title: 'Avatar', icon: 'i-lucide-circle', link: '/components/avatar' },
          { title: 'Badge', icon: 'i-lucide-circle', link: '/components/badge' },
          { title: 'Breadcrumb', icon: 'i-lucide-circle', link: '/components/breadcrumb' },
          { title: 'Button', icon: 'i-lucide-circle', link: '/components/button' },
          { title: 'Calendar', icon: 'i-lucide-circle', link: '/components/calendar' },
          { title: 'Card', icon: 'i-lucide-circle', link: '/components/card' },
          { title: 'Carousel', icon: 'i-lucide-circle', link: '/components/carousel' },
          { title: 'Checkbox', icon: 'i-lucide-circle', link: '/components/checkbox' },
          { title: 'Collapsible', icon: 'i-lucide-circle', link: '/components/collapsible' },
          { title: 'Combobox', icon: 'i-lucide-circle', link: '/components/combobox' },
          { title: 'Command', icon: 'i-lucide-circle', link: '/components/command' },
          { title: 'Context Menu', icon: 'i-lucide-circle', link: '/components/context-menu' },
          { title: 'Dialog', icon: 'i-lucide-circle', link: '/components/dialog' },
          { title: 'Drawer', icon: 'i-lucide-circle', link: '/components/drawer' },
          { title: 'Dropdown Menu', icon: 'i-lucide-circle', link: '/components/dropdown-menu' },
          { title: 'Form', icon: 'i-lucide-circle', link: '/components/form' },
          { title: 'Hover Card', icon: 'i-lucide-circle', link: '/components/hover-card' },
          { title: 'Input', icon: 'i-lucide-circle', link: '/components/input' },
          { title: 'Item', icon: 'i-lucide-circle', link: '/components/item', new: true },
          { title: 'kbd', icon: 'i-lucide-circle', link: '/components/kbd', new: true },
          { title: 'Label', icon: 'i-lucide-circle', link: '/components/label' },
          { title: 'Menubar', icon: 'i-lucide-circle', link: '/components/menubar' },
          { title: 'Navigation Menu', icon: 'i-lucide-circle', link: '/components/navigation-menu' },
          { title: 'Number Field', icon: 'i-lucide-circle', link: '/components/number-field' },
          { title: 'Pagination', icon: 'i-lucide-circle', link: '/components/pagination' },
          { title: 'PIN Input', icon: 'i-lucide-circle', link: '/components/pin-input' },
          { title: 'Popover', icon: 'i-lucide-circle', link: '/components/popover' },
          { title: 'Progress', icon: 'i-lucide-circle', link: '/components/progress' },
          { title: 'Radio Group', icon: 'i-lucide-circle', link: '/components/radio-group' },
          { title: 'Range Calendar', icon: 'i-lucide-circle', link: '/components/range-calendar' },
          { title: 'Resizable', icon: 'i-lucide-circle', link: '/components/resizable' },
          { title: 'Scroll Area', icon: 'i-lucide-circle', link: '/components/scroll-area' },
          { title: 'Select', icon: 'i-lucide-circle', link: '/components/select' },
          { title: 'Separator', icon: 'i-lucide-circle', link: '/components/separator' },
          { title: 'Sheet', icon: 'i-lucide-circle', link: '/components/sheet' },
          { title: 'Skeleton', icon: 'i-lucide-circle', link: '/components/skeleton' },
          { title: 'Slider', icon: 'i-lucide-circle', link: '/components/slider' },
          { title: 'Sonner', icon: 'i-lucide-circle', link: '/components/sonner' },
          { title: 'Stepper', icon: 'i-lucide-circle', link: '/components/stepper' },
          { title: 'Switch', icon: 'i-lucide-circle', link: '/components/switch' },
          { title: 'Table', icon: 'i-lucide-circle', link: '/components/table' },
          { title: 'Tabs', icon: 'i-lucide-circle', link: '/components/tabs' },
          { title: 'Tags Input', icon: 'i-lucide-circle', link: '/components/tags-input' },
          { title: 'Textarea', icon: 'i-lucide-circle', link: '/components/textarea' },
          { title: 'Toast', icon: 'i-lucide-circle', link: '/components/toast' },
          { title: 'Toggle', icon: 'i-lucide-circle', link: '/components/toggle' },
          { title: 'Toggle Group', icon: 'i-lucide-circle', link: '/components/toggle-group' },
          { title: 'Tooltip', icon: 'i-lucide-circle', link: '/components/tooltip' },
        ],
      },
    ],
  },
  {
    heading: 'Documentation',
    headingKey: 'nav.documentation',
    items: [
      {
        title: 'Documentation',
        titleKey: 'nav.documentation',
        icon: 'i-lucide-file-code',
        link: '/docs',
        new: true,
      },
    ],
  },
]

export const navMenuBottom: NavMenuItems = [
  {
    title: 'Help & Support',
    titleKey: 'nav.helpSupport',
    icon: 'i-lucide-circle-help',
    link: '/docs',
  },
  {
    title: 'Feedback',
    titleKey: 'nav.feedback',
    icon: 'i-lucide-send',
    link: '/docs',
  },
]
