<script setup lang="ts">
import type { SalesDocument } from '~/composables/useSalesDocument'

const statusOptions = [
  { label: 'Draft', value: 'Draft' },
  { label: 'Sent', value: 'Sent' },
  { label: 'Paid', value: 'Paid' },
  { label: 'Overdue', value: 'Overdue' },
  { label: 'Cancelled', value: 'Cancelled' },
]

const extraFields = [
  { key: 'dueDate', label: 'Due Date', type: 'date' },
  { key: 'paidAmount', label: 'Amount Paid ($)', type: 'number', placeholder: '0' },
  { key: 'paymentMethod', label: 'Payment Method', placeholder: 'Wire Transfer, Check, Credit Card...' },
]

const seedData: SalesDocument[] = [
  {
    id: 'i1',
    number: 'INV-2026-078',
    client: 'Riverside Custom Homes',
    clientEmail: 'accounts@riversidecustomhomes.com',
    clientAddress: '3480 Washtenaw Ave, Ann Arbor, MI 48104',
    status: 'Paid',
    date: '2026-01-15',
    dueDate: '2026-02-15',
    paidAmount: 36983.40,
    paymentMethod: 'Wire Transfer',
    notes: 'Full payment received Feb 10. White oak install completed on schedule. Bank ref: WR-2026-882.',
    lineItems: [
      { id: 'li1', description: 'White Oak Hardwood Supply (3/4" x 5")', quantity: 2400, unitPrice: 6.50, discount: 5, tax: 6 },
      { id: 'li2', description: 'Herringbone Pattern Install — Foyer (180 sqft)', quantity: 180, unitPrice: 12.00, discount: 0, tax: 6 },
      { id: 'li3', description: 'Standard Hardwood Installation (2220 sqft)', quantity: 2220, unitPrice: 4.75, discount: 0, tax: 6 },
      { id: 'li4', description: 'Sand & Finish — 3 Coats Oil-Based Poly', quantity: 2400, unitPrice: 2.50, discount: 0, tax: 6 },
      { id: 'li5', description: 'Subfloor Prep & Moisture Barrier', quantity: 2400, unitPrice: 0.85, discount: 0, tax: 6 },
    ],
    subtotal: 34890,
    taxTotal: 2093.40,
    discountTotal: 780,
    total: 36983.40,
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'i2',
    number: 'INV-2026-079',
    client: 'The Patterson Residence',
    clientEmail: 'jpatterson@gmail.com',
    clientAddress: '1872 Geddes Rd, Ann Arbor, MI 48104',
    status: 'Paid',
    date: '2026-02-01',
    dueDate: '2026-03-01',
    paidAmount: 5763.75,
    paymentMethod: 'Check',
    notes: 'Check #4412 received Feb 20. Refinish job completed. Client very satisfied with Jacobean stain.',
    lineItems: [
      { id: 'li6', description: 'Hardwood Floor Sanding (Drum & Edge)', quantity: 950, unitPrice: 2.00, discount: 0, tax: 6 },
      { id: 'li7', description: 'Stain Application — Jacobean', quantity: 950, unitPrice: 1.50, discount: 0, tax: 6 },
      { id: 'li8', description: 'Finish — 3 Coats Water-Based Poly', quantity: 950, unitPrice: 1.75, discount: 0, tax: 6 },
      { id: 'li9', description: 'Furniture Moving & Protection', quantity: 1, unitPrice: 450, discount: 0, tax: 6 },
    ],
    subtotal: 5437.50,
    taxTotal: 326.25,
    discountTotal: 0,
    total: 5763.75,
    createdAt: '2026-02-01T11:00:00Z',
  },
  {
    id: 'i3',
    number: 'INV-2026-080',
    client: 'Dexter Community Schools',
    clientEmail: 'maintenance@dexterschools.org',
    clientAddress: '7714 Ann Arbor St, Dexter, MI 48130',
    status: 'Overdue',
    date: '2026-01-05',
    dueDate: '2026-02-05',
    paidAmount: 0,
    paymentMethod: '',
    notes: 'Gym floor refinish completed Dec 28. Invoice overdue — second reminder sent Feb 10. Awaiting district PO process.',
    lineItems: [
      { id: 'li10', description: 'Gym Floor Sanding — Heavy Duty', quantity: 6400, unitPrice: 1.75, discount: 0, tax: 0 },
      { id: 'li11', description: 'Game Line Painting (Basketball + Volleyball)', quantity: 1, unitPrice: 4500, discount: 0, tax: 0 },
      { id: 'li12', description: 'Low-VOC Gym Floor Finish — 3 Coats', quantity: 6400, unitPrice: 2.25, discount: 5, tax: 0 },
      { id: 'li13', description: 'Logo Re-application (Center Court)', quantity: 1, unitPrice: 1800, discount: 0, tax: 0 },
    ],
    subtotal: 31900,
    taxTotal: 0,
    discountTotal: 720,
    total: 31180,
    createdAt: '2026-01-05T08:30:00Z',
  },
  {
    id: 'i4',
    number: 'INV-2026-081',
    client: 'Harper Renovation Co.',
    clientEmail: 'finance@harperreno.com',
    clientAddress: '524 S State St, Ann Arbor, MI 48104',
    status: 'Paid',
    date: '2026-01-20',
    dueDate: '2026-02-04',
    paidAmount: 6256.12,
    paymentMethod: 'Credit Card',
    notes: 'Staircase project completed Jan 18. Paid in full via corporate card on Jan 22.',
    lineItems: [
      { id: 'li14', description: 'Stair Tread Supply — Red Oak (14 treads)', quantity: 14, unitPrice: 65, discount: 0, tax: 6 },
      { id: 'li15', description: 'Stair Riser Supply — Red Oak', quantity: 14, unitPrice: 28, discount: 0, tax: 6 },
      { id: 'li16', description: 'Staircase Installation & Finishing', quantity: 1, unitPrice: 3200, discount: 0, tax: 6 },
      { id: 'li17', description: 'Baluster & Railing Refinish', quantity: 1, unitPrice: 1400, discount: 10, tax: 6 },
    ],
    subtotal: 5902,
    taxTotal: 354.12,
    discountTotal: 140,
    total: 6256.12,
    createdAt: '2026-01-20T14:00:00Z',
  },
  {
    id: 'i5',
    number: 'INV-2026-082',
    client: 'Lakeshore Properties LLC',
    clientEmail: 'accounting@lakeshoreprops.com',
    clientAddress: '2200 Green Rd, Suite 150, Ann Arbor, MI 48105',
    status: 'Sent',
    date: '2026-02-10',
    dueDate: '2026-03-10',
    paidAmount: 0,
    paymentMethod: '',
    notes: 'Rental unit turnover — hardwood repair and refinish in 3 units. Net 30 terms. Invoice sent via email.',
    lineItems: [
      { id: 'li18', description: 'Board Replacement — Red Oak (damaged sections)', quantity: 120, unitPrice: 8.50, discount: 0, tax: 6 },
      { id: 'li19', description: 'Full Sand & Refinish — Unit 3A (680 sqft)', quantity: 680, unitPrice: 3.25, discount: 0, tax: 6 },
      { id: 'li20', description: 'Full Sand & Refinish — Unit 3B (720 sqft)', quantity: 720, unitPrice: 3.25, discount: 0, tax: 6 },
      { id: 'li21', description: 'Screen & Recoat — Unit 3C (650 sqft)', quantity: 650, unitPrice: 1.75, discount: 0, tax: 6 },
      { id: 'li22', description: 'Transition Strips & Thresholds', quantity: 8, unitPrice: 45, discount: 0, tax: 6 },
    ],
    subtotal: 7247.50,
    taxTotal: 434.85,
    discountTotal: 0,
    total: 7682.35,
    createdAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'i6',
    number: 'INV-2026-083',
    client: 'Wolverine Brewing Company',
    clientEmail: 'gm@wolverinebeer.com',
    clientAddress: '2880 W Liberty St, Ann Arbor, MI 48103',
    status: 'Paid',
    date: '2026-01-28',
    dueDate: '2026-02-28',
    paidAmount: 14310,
    paymentMethod: 'ACH Transfer',
    notes: 'Taproom floor sand and commercial finish. Paid ahead of schedule — loyal customer discount applied.',
    lineItems: [
      { id: 'li23', description: 'Commercial Floor Sanding (1800 sqft bar area)', quantity: 1800, unitPrice: 2.50, discount: 0, tax: 6 },
      { id: 'li24', description: 'Commercial-Grade Finish — 4 Coats Moisture-Cure', quantity: 1800, unitPrice: 3.25, discount: 10, tax: 6 },
      { id: 'li25', description: 'Bar Counter Refinish (Solid Maple)', quantity: 1, unitPrice: 2800, discount: 0, tax: 6 },
      { id: 'li26', description: 'After-Hours Work Premium (3 nights)', quantity: 3, unitPrice: 650, discount: 0, tax: 6 },
    ],
    subtotal: 13500,
    taxTotal: 810,
    discountTotal: 585,
    total: 14310,
    createdAt: '2026-01-28T12:00:00Z',
  },
  {
    id: 'i7',
    number: 'INV-2026-084',
    client: 'Saline Area Schools',
    clientEmail: 'facilities@salineschools.org',
    clientAddress: '7190 N Maple Rd, Saline, MI 48176',
    status: 'Draft',
    date: '2026-02-12',
    dueDate: '2026-03-12',
    paidAmount: 0,
    paymentMethod: '',
    notes: 'Summer gym floor refinish project for 2 gymnasiums. Pending board approval before sending.',
    lineItems: [
      { id: 'li27', description: 'Gym Floor Sanding — Main Gym (8200 sqft)', quantity: 8200, unitPrice: 1.75, discount: 0, tax: 0 },
      { id: 'li28', description: 'Gym Floor Sanding — Aux Gym (4800 sqft)', quantity: 4800, unitPrice: 1.75, discount: 0, tax: 0 },
      { id: 'li29', description: 'Game Lines — Basketball & Volleyball (2 gyms)', quantity: 2, unitPrice: 4500, discount: 5, tax: 0 },
      { id: 'li30', description: 'Gym Finish — 3 Coats Low-VOC (13000 sqft)', quantity: 13000, unitPrice: 2.00, discount: 0, tax: 0 },
      { id: 'li31', description: 'School Logo Re-paint (2 logos)', quantity: 2, unitPrice: 2200, discount: 0, tax: 0 },
    ],
    subtotal: 57150,
    taxTotal: 0,
    discountTotal: 450,
    total: 56700,
    createdAt: '2026-02-12T16:30:00Z',
  },
  {
    id: 'i8',
    number: 'INV-2026-085',
    client: 'Michigan Medicine — Taubman Center',
    clientEmail: 'facilityops@med.umich.edu',
    clientAddress: '1500 E Medical Center Dr, Ann Arbor, MI 48109',
    status: 'Overdue',
    date: '2026-01-01',
    dueDate: '2026-01-31',
    paidAmount: 0,
    paymentMethod: '',
    notes: 'Administrative hallway refinish completed Dec 26. Third overdue notice sent. University PO system delay.',
    lineItems: [
      { id: 'li32', description: 'Commercial Sand & Refinish (2400 sqft)', quantity: 2400, unitPrice: 3.50, discount: 0, tax: 0 },
      { id: 'li33', description: 'Moisture-Cure Urethane Finish — 3 Coats', quantity: 2400, unitPrice: 2.75, discount: 0, tax: 0 },
      { id: 'li34', description: 'Weekend Work Premium', quantity: 1, unitPrice: 1800, discount: 0, tax: 0 },
    ],
    subtotal: 16800,
    taxTotal: 0,
    discountTotal: 0,
    total: 16800,
    createdAt: '2026-01-01T06:00:00Z',
  },
]
</script>

<template>
  <SalesDocumentPage
    store-key="sales-invoices-v2"
    doc-type="Invoice"
    title="Invoices"
    description="Generate, send, and track invoices with payment reminders"
    icon="i-lucide-receipt"
    :status-options="statusOptions"
    :extra-fields="extraFields"
    :initial-data="seedData"
  />
</template>
